CREATE TABLE `users` (
  `id` int PRIMARY KEY AUTO_INCREMENT,
  `name` varchar(255),
  `email` varchar(255),
  `password` varchar(255)
);

CREATE TABLE `diary` (
  `id` int PRIMARY KEY,
  `title` varchar(255),
  `created_at` timestamp,
  `content` varchar(255),
  `user_id` int
);

CREATE TABLE `diary_entry` (
  `id` int PRIMARY KEY,
  `entry` varchar(255)
);

ALTER TABLE `users` ADD FOREIGN KEY (`id`) REFERENCES `diary` (`user_id`);

ALTER TABLE `diary` ADD FOREIGN KEY (`id`) REFERENCES `diary_entry` (`id`);
insert into MOCK_DATA (id, entry) values (1, '542 35');
insert into MOCK_DATA (id, entry) values (2, '30250');
insert into MOCK_DATA (id, entry) values (3, null);
insert into MOCK_DATA (id, entry) values (4, null);
insert into MOCK_DATA (id, entry) values (5, null);
insert into MOCK_DATA (id, entry) values (6, '6512');
insert into MOCK_DATA (id, entry) values (7, null);
insert into MOCK_DATA (id, entry) values (8, '30096');
insert into MOCK_DATA (id, entry) values (9, '65940-000');
insert into MOCK_DATA (id, entry) values (10, null);
insert into MOCK_DATA (id, entry) values (11, '6160-402');
insert into MOCK_DATA (id, entry) values (12, null);
insert into MOCK_DATA (id, entry) values (13, null);
insert into MOCK_DATA (id, entry) values (14, '15775-000');
insert into MOCK_DATA (id, entry) values (15, null);
insert into MOCK_DATA (id, entry) values (16, '939-1351');
insert into MOCK_DATA (id, entry) values (17, null);
insert into MOCK_DATA (id, entry) values (18, '5667');
insert into MOCK_DATA (id, entry) values (19, null);
insert into MOCK_DATA (id, entry) values (20, null);
insert into MOCK_DATA (id, entry) values (21, null);
insert into MOCK_DATA (id, entry) values (22, '8400-017');
insert into MOCK_DATA (id, entry) values (23, '79480');
insert into MOCK_DATA (id, entry) values (24, null);
insert into MOCK_DATA (id, entry) values (25, '85053');
insert into MOCK_DATA (id, entry) values (26, '18-421');
insert into MOCK_DATA (id, entry) values (27, null);
insert into MOCK_DATA (id, entry) values (28, null);
insert into MOCK_DATA (id, entry) values (29, '5040');
insert into MOCK_DATA (id, entry) values (30, '87-165');
insert into MOCK_DATA (id, entry) values (31, null);
insert into MOCK_DATA (id, entry) values (32, null);
insert into MOCK_DATA (id, entry) values (33, null);
insert into MOCK_DATA (id, entry) values (34, null);
insert into MOCK_DATA (id, entry) values (35, null);
insert into MOCK_DATA (id, entry) values (36, null);
insert into MOCK_DATA (id, entry) values (37, null);
insert into MOCK_DATA (id, entry) values (38, '5017');
insert into MOCK_DATA (id, entry) values (39, null);
insert into MOCK_DATA (id, entry) values (40, '793 51');
insert into MOCK_DATA (id, entry) values (41, null);
insert into MOCK_DATA (id, entry) values (42, '790 01');
insert into MOCK_DATA (id, entry) values (43, null);
insert into MOCK_DATA (id, entry) values (44, null);
insert into MOCK_DATA (id, entry) values (45, '385141');
insert into MOCK_DATA (id, entry) values (46, null);
insert into MOCK_DATA (id, entry) values (47, null);
insert into MOCK_DATA (id, entry) values (48, null);
insert into MOCK_DATA (id, entry) values (49, '422343');
insert into MOCK_DATA (id, entry) values (50, null);
insert into MOCK_DATA (id, entry) values (51, null);
insert into MOCK_DATA (id, entry) values (52, null);
insert into MOCK_DATA (id, entry) values (53, null);
insert into MOCK_DATA (id, entry) values (54, null);
insert into MOCK_DATA (id, entry) values (55, '14085 CEDEX 9');
insert into MOCK_DATA (id, entry) values (56, '7300');
insert into MOCK_DATA (id, entry) values (57, '23161');
insert into MOCK_DATA (id, entry) values (58, '56140');
insert into MOCK_DATA (id, entry) values (59, '84913 CEDEX 9');
insert into MOCK_DATA (id, entry) values (60, null);
insert into MOCK_DATA (id, entry) values (61, null);
insert into MOCK_DATA (id, entry) values (62, null);
insert into MOCK_DATA (id, entry) values (63, null);
insert into MOCK_DATA (id, entry) values (64, '49082');
insert into MOCK_DATA (id, entry) values (65, null);
insert into MOCK_DATA (id, entry) values (66, '9500-701');
insert into MOCK_DATA (id, entry) values (67, null);
insert into MOCK_DATA (id, entry) values (68, '66110');
insert into MOCK_DATA (id, entry) values (69, null);
insert into MOCK_DATA (id, entry) values (70, null);
insert into MOCK_DATA (id, entry) values (71, null);
insert into MOCK_DATA (id, entry) values (72, null);
insert into MOCK_DATA (id, entry) values (73, null);
insert into MOCK_DATA (id, entry) values (74, null);
insert into MOCK_DATA (id, entry) values (75, null);
insert into MOCK_DATA (id, entry) values (76, null);
insert into MOCK_DATA (id, entry) values (77, '2604');
insert into MOCK_DATA (id, entry) values (78, null);
insert into MOCK_DATA (id, entry) values (79, null);
insert into MOCK_DATA (id, entry) values (80, '22-413');
insert into MOCK_DATA (id, entry) values (81, null);
insert into MOCK_DATA (id, entry) values (82, 'H62');
insert into MOCK_DATA (id, entry) values (83, null);
insert into MOCK_DATA (id, entry) values (84, null);
insert into MOCK_DATA (id, entry) values (85, null);
insert into MOCK_DATA (id, entry) values (86, null);
insert into MOCK_DATA (id, entry) values (87, null);
insert into MOCK_DATA (id, entry) values (88, '6001');
insert into MOCK_DATA (id, entry) values (89, null);
insert into MOCK_DATA (id, entry) values (90, null);
insert into MOCK_DATA (id, entry) values (91, '59343-000');
insert into MOCK_DATA (id, entry) values (92, '2101');
insert into MOCK_DATA (id, entry) values (93, '0915');
insert into MOCK_DATA (id, entry) values (94, null);
insert into MOCK_DATA (id, entry) values (95, null);
insert into MOCK_DATA (id, entry) values (96, '157944');
insert into MOCK_DATA (id, entry) values (97, 'ZTN');
insert into MOCK_DATA (id, entry) values (98, null);
insert into MOCK_DATA (id, entry) values (99, '177089');
insert into MOCK_DATA (id, entry) values (100, null);
insert into MOCK_DATA (id, entry) values (101, '057428');
insert into MOCK_DATA (id, entry) values (102, '42704 CEDEX');
insert into MOCK_DATA (id, entry) values (103, null);
insert into MOCK_DATA (id, entry) values (104, '357637');
insert into MOCK_DATA (id, entry) values (105, '39216');
insert into MOCK_DATA (id, entry) values (106, '65213-000');
insert into MOCK_DATA (id, entry) values (107, '353318');
insert into MOCK_DATA (id, entry) values (108, null);
insert into MOCK_DATA (id, entry) values (109, '6803');
insert into MOCK_DATA (id, entry) values (110, null);
insert into MOCK_DATA (id, entry) values (111, null);
insert into MOCK_DATA (id, entry) values (112, '932-0056');
insert into MOCK_DATA (id, entry) values (113, '610-0331');
insert into MOCK_DATA (id, entry) values (114, null);
insert into MOCK_DATA (id, entry) values (115, null);
insert into MOCK_DATA (id, entry) values (116, '347703');
insert into MOCK_DATA (id, entry) values (117, null);
insert into MOCK_DATA (id, entry) values (118, '4210');
insert into MOCK_DATA (id, entry) values (119, null);
insert into MOCK_DATA (id, entry) values (120, null);
insert into MOCK_DATA (id, entry) values (121, '598 93');
insert into MOCK_DATA (id, entry) values (122, '79160');
insert into MOCK_DATA (id, entry) values (123, '53100');
insert into MOCK_DATA (id, entry) values (124, null);
insert into MOCK_DATA (id, entry) values (125, '17024 CEDEX 1');
insert into MOCK_DATA (id, entry) values (126, null);
insert into MOCK_DATA (id, entry) values (127, null);
insert into MOCK_DATA (id, entry) values (128, null);
insert into MOCK_DATA (id, entry) values (129, null);
insert into MOCK_DATA (id, entry) values (130, 'L-5465');
insert into MOCK_DATA (id, entry) values (131, null);
insert into MOCK_DATA (id, entry) values (132, null);
insert into MOCK_DATA (id, entry) values (133, null);
insert into MOCK_DATA (id, entry) values (134, '21460');
insert into MOCK_DATA (id, entry) values (135, null);
insert into MOCK_DATA (id, entry) values (136, '45310');
insert into MOCK_DATA (id, entry) values (137, null);
insert into MOCK_DATA (id, entry) values (138, null);
insert into MOCK_DATA (id, entry) values (139, '40914');
insert into MOCK_DATA (id, entry) values (140, null);
insert into MOCK_DATA (id, entry) values (141, '591 46');
insert into MOCK_DATA (id, entry) values (142, null);
insert into MOCK_DATA (id, entry) values (143, '15290-000');
insert into MOCK_DATA (id, entry) values (144, '4520-104');
insert into MOCK_DATA (id, entry) values (145, '679005');
insert into MOCK_DATA (id, entry) values (146, '686058');
insert into MOCK_DATA (id, entry) values (147, '3070-635');
insert into MOCK_DATA (id, entry) values (148, '2201');
insert into MOCK_DATA (id, entry) values (149, '25501');
insert into MOCK_DATA (id, entry) values (150, '8201');
insert into MOCK_DATA (id, entry) values (151, null);
insert into MOCK_DATA (id, entry) values (152, null);
insert into MOCK_DATA (id, entry) values (153, null);
insert into MOCK_DATA (id, entry) values (154, null);
insert into MOCK_DATA (id, entry) values (155, '49700-000');
insert into MOCK_DATA (id, entry) values (156, null);
insert into MOCK_DATA (id, entry) values (157, '270-0105');
insert into MOCK_DATA (id, entry) values (158, '50700');
insert into MOCK_DATA (id, entry) values (159, null);
insert into MOCK_DATA (id, entry) values (160, null);
insert into MOCK_DATA (id, entry) values (161, '74-320');
insert into MOCK_DATA (id, entry) values (162, null);
insert into MOCK_DATA (id, entry) values (163, null);
insert into MOCK_DATA (id, entry) values (164, '43-365');
insert into MOCK_DATA (id, entry) values (165, null);
insert into MOCK_DATA (id, entry) values (166, null);
insert into MOCK_DATA (id, entry) values (167, null);
insert into MOCK_DATA (id, entry) values (168, '413362');
insert into MOCK_DATA (id, entry) values (169, null);
insert into MOCK_DATA (id, entry) values (170, '35530-000');
insert into MOCK_DATA (id, entry) values (171, '665709');
insert into MOCK_DATA (id, entry) values (172, null);
insert into MOCK_DATA (id, entry) values (173, '751 19');
insert into MOCK_DATA (id, entry) values (174, '64-810');
insert into MOCK_DATA (id, entry) values (175, '78000-000');
insert into MOCK_DATA (id, entry) values (176, '49901');
insert into MOCK_DATA (id, entry) values (177, '61300');
insert into MOCK_DATA (id, entry) values (178, null);
insert into MOCK_DATA (id, entry) values (179, '58095');
insert into MOCK_DATA (id, entry) values (180, null);
insert into MOCK_DATA (id, entry) values (181, null);
insert into MOCK_DATA (id, entry) values (182, null);
insert into MOCK_DATA (id, entry) values (183, null);
insert into MOCK_DATA (id, entry) values (184, '2840');
insert into MOCK_DATA (id, entry) values (185, '2530-009');
insert into MOCK_DATA (id, entry) values (186, '427650');
insert into MOCK_DATA (id, entry) values (187, null);
insert into MOCK_DATA (id, entry) values (188, null);
insert into MOCK_DATA (id, entry) values (189, null);
insert into MOCK_DATA (id, entry) values (190, null);
insert into MOCK_DATA (id, entry) values (191, null);
insert into MOCK_DATA (id, entry) values (192, '35650-000');
insert into MOCK_DATA (id, entry) values (193, '704038');
insert into MOCK_DATA (id, entry) values (194, '9413');
insert into MOCK_DATA (id, entry) values (195, null);
insert into MOCK_DATA (id, entry) values (196, null);
insert into MOCK_DATA (id, entry) values (197, '6501');
insert into MOCK_DATA (id, entry) values (198, '2519');
insert into MOCK_DATA (id, entry) values (199, null);
insert into MOCK_DATA (id, entry) values (200, '664 55');
insert into MOCK_DATA (id, entry) values (201, null);
insert into MOCK_DATA (id, entry) values (202, null);
insert into MOCK_DATA (id, entry) values (203, null);
insert into MOCK_DATA (id, entry) values (204, '0280');
insert into MOCK_DATA (id, entry) values (205, '627603');
insert into MOCK_DATA (id, entry) values (206, '11878 CEDEX 9');
insert into MOCK_DATA (id, entry) values (207, null);
insert into MOCK_DATA (id, entry) values (208, null);
insert into MOCK_DATA (id, entry) values (209, null);
insert into MOCK_DATA (id, entry) values (210, null);
insert into MOCK_DATA (id, entry) values (211, '822-0034');
insert into MOCK_DATA (id, entry) values (212, null);
insert into MOCK_DATA (id, entry) values (213, null);
insert into MOCK_DATA (id, entry) values (214, '27500-000');
insert into MOCK_DATA (id, entry) values (215, '92000-000');
insert into MOCK_DATA (id, entry) values (216, '27040');
insert into MOCK_DATA (id, entry) values (217, null);
insert into MOCK_DATA (id, entry) values (218, null);
insert into MOCK_DATA (id, entry) values (219, '4809');
insert into MOCK_DATA (id, entry) values (220, '48140');
insert into MOCK_DATA (id, entry) values (221, null);
insert into MOCK_DATA (id, entry) values (222, '88598-000');
insert into MOCK_DATA (id, entry) values (223, '4142');
insert into MOCK_DATA (id, entry) values (224, 'K6V');
insert into MOCK_DATA (id, entry) values (225, '366703');
insert into MOCK_DATA (id, entry) values (226, '97-280');
insert into MOCK_DATA (id, entry) values (227, null);
insert into MOCK_DATA (id, entry) values (228, '2420-031');
insert into MOCK_DATA (id, entry) values (229, '356126');
insert into MOCK_DATA (id, entry) values (230, null);
insert into MOCK_DATA (id, entry) values (231, '6743');
insert into MOCK_DATA (id, entry) values (232, 'V5M');
insert into MOCK_DATA (id, entry) values (233, '10705');
insert into MOCK_DATA (id, entry) values (234, null);
insert into MOCK_DATA (id, entry) values (235, '393194');
insert into MOCK_DATA (id, entry) values (236, '45250');
insert into MOCK_DATA (id, entry) values (237, '73031 CEDEX');
insert into MOCK_DATA (id, entry) values (238, null);
insert into MOCK_DATA (id, entry) values (239, null);
insert into MOCK_DATA (id, entry) values (240, null);
insert into MOCK_DATA (id, entry) values (241, null);
insert into MOCK_DATA (id, entry) values (242, '46005');
insert into MOCK_DATA (id, entry) values (243, null);
insert into MOCK_DATA (id, entry) values (244, null);
insert into MOCK_DATA (id, entry) values (245, '081048');
insert into MOCK_DATA (id, entry) values (246, null);
insert into MOCK_DATA (id, entry) values (247, '1748');
insert into MOCK_DATA (id, entry) values (248, null);
insert into MOCK_DATA (id, entry) values (249, null);
insert into MOCK_DATA (id, entry) values (250, '141901');
insert into MOCK_DATA (id, entry) values (251, null);
insert into MOCK_DATA (id, entry) values (252, null);
insert into MOCK_DATA (id, entry) values (253, '06-210');
insert into MOCK_DATA (id, entry) values (254, null);
insert into MOCK_DATA (id, entry) values (255, null);
insert into MOCK_DATA (id, entry) values (256, null);
insert into MOCK_DATA (id, entry) values (257, null);
insert into MOCK_DATA (id, entry) values (258, '153668');
insert into MOCK_DATA (id, entry) values (259, null);
insert into MOCK_DATA (id, entry) values (260, '48211');
insert into MOCK_DATA (id, entry) values (261, null);
insert into MOCK_DATA (id, entry) values (262, null);
insert into MOCK_DATA (id, entry) values (263, '691 45');
insert into MOCK_DATA (id, entry) values (264, '43-450');
insert into MOCK_DATA (id, entry) values (265, '3605');
insert into MOCK_DATA (id, entry) values (266, null);
insert into MOCK_DATA (id, entry) values (267, '3025-419');
insert into MOCK_DATA (id, entry) values (268, null);
insert into MOCK_DATA (id, entry) values (269, '969-1783');
insert into MOCK_DATA (id, entry) values (270, null);
insert into MOCK_DATA (id, entry) values (271, null);
insert into MOCK_DATA (id, entry) values (272, '4550-356');
insert into MOCK_DATA (id, entry) values (273, null);
insert into MOCK_DATA (id, entry) values (274, null);
insert into MOCK_DATA (id, entry) values (275, null);
insert into MOCK_DATA (id, entry) values (276, null);
insert into MOCK_DATA (id, entry) values (277, '40130');
insert into MOCK_DATA (id, entry) values (278, null);
insert into MOCK_DATA (id, entry) values (279, null);
insert into MOCK_DATA (id, entry) values (280, null);
insert into MOCK_DATA (id, entry) values (281, '4336');
insert into MOCK_DATA (id, entry) values (282, null);
insert into MOCK_DATA (id, entry) values (283, '697-1201');
insert into MOCK_DATA (id, entry) values (284, '725 96');
insert into MOCK_DATA (id, entry) values (285, null);
insert into MOCK_DATA (id, entry) values (286, '95974 CEDEX 2');
insert into MOCK_DATA (id, entry) values (287, null);
insert into MOCK_DATA (id, entry) values (288, '0915');
insert into MOCK_DATA (id, entry) values (289, null);
insert into MOCK_DATA (id, entry) values (290, null);
insert into MOCK_DATA (id, entry) values (291, null);
insert into MOCK_DATA (id, entry) values (292, '664 55');
insert into MOCK_DATA (id, entry) values (293, null);
insert into MOCK_DATA (id, entry) values (294, '63-600');
insert into MOCK_DATA (id, entry) values (295, null);
insert into MOCK_DATA (id, entry) values (296, null);
insert into MOCK_DATA (id, entry) values (297, '2865-613');
insert into MOCK_DATA (id, entry) values (298, null);
insert into MOCK_DATA (id, entry) values (299, null);
insert into MOCK_DATA (id, entry) values (300, null);
insert into MOCK_DATA (id, entry) values (301, null);
insert into MOCK_DATA (id, entry) values (302, null);
insert into MOCK_DATA (id, entry) values (303, null);
insert into MOCK_DATA (id, entry) values (304, null);
insert into MOCK_DATA (id, entry) values (305, null);
insert into MOCK_DATA (id, entry) values (306, '4203');
insert into MOCK_DATA (id, entry) values (307, null);
insert into MOCK_DATA (id, entry) values (308, '99507');
insert into MOCK_DATA (id, entry) values (309, null);
insert into MOCK_DATA (id, entry) values (310, null);
insert into MOCK_DATA (id, entry) values (311, '519 81');
insert into MOCK_DATA (id, entry) values (312, '78364 CEDEX');
insert into MOCK_DATA (id, entry) values (313, '3250');
insert into MOCK_DATA (id, entry) values (314, '75700-000');
insert into MOCK_DATA (id, entry) values (315, '3725');
insert into MOCK_DATA (id, entry) values (316, null);
insert into MOCK_DATA (id, entry) values (317, null);
insert into MOCK_DATA (id, entry) values (318, null);
insert into MOCK_DATA (id, entry) values (319, null);
insert into MOCK_DATA (id, entry) values (320, null);
insert into MOCK_DATA (id, entry) values (321, null);
insert into MOCK_DATA (id, entry) values (322, null);
insert into MOCK_DATA (id, entry) values (323, '999-3503');
insert into MOCK_DATA (id, entry) values (324, null);
insert into MOCK_DATA (id, entry) values (325, '44200');
insert into MOCK_DATA (id, entry) values (326, null);
insert into MOCK_DATA (id, entry) values (327, null);
insert into MOCK_DATA (id, entry) values (328, null);
insert into MOCK_DATA (id, entry) values (329, null);
insert into MOCK_DATA (id, entry) values (330, null);
insert into MOCK_DATA (id, entry) values (331, null);
insert into MOCK_DATA (id, entry) values (332, '731568');
insert into MOCK_DATA (id, entry) values (333, null);
insert into MOCK_DATA (id, entry) values (334, null);
insert into MOCK_DATA (id, entry) values (335, '763547');
insert into MOCK_DATA (id, entry) values (336, '95-036');
insert into MOCK_DATA (id, entry) values (337, '747 44');
insert into MOCK_DATA (id, entry) values (338, '590 73');
insert into MOCK_DATA (id, entry) values (339, '2070-305');
insert into MOCK_DATA (id, entry) values (340, '9012');
insert into MOCK_DATA (id, entry) values (341, null);
insert into MOCK_DATA (id, entry) values (342, null);
insert into MOCK_DATA (id, entry) values (343, '234008');
insert into MOCK_DATA (id, entry) values (344, null);
insert into MOCK_DATA (id, entry) values (345, '4203');
insert into MOCK_DATA (id, entry) values (346, '37-224');
insert into MOCK_DATA (id, entry) values (347, '576 24');
insert into MOCK_DATA (id, entry) values (348, '35102 CEDEX 3');
insert into MOCK_DATA (id, entry) values (349, null);
insert into MOCK_DATA (id, entry) values (350, null);
insert into MOCK_DATA (id, entry) values (351, '32274');
insert into MOCK_DATA (id, entry) values (352, '3571');
insert into MOCK_DATA (id, entry) values (353, '953 34');
insert into MOCK_DATA (id, entry) values (354, '3560-136');
insert into MOCK_DATA (id, entry) values (355, null);
insert into MOCK_DATA (id, entry) values (356, null);
insert into MOCK_DATA (id, entry) values (357, null);
insert into MOCK_DATA (id, entry) values (358, '798 45');
insert into MOCK_DATA (id, entry) values (359, '64704 CEDEX');
insert into MOCK_DATA (id, entry) values (360, null);
insert into MOCK_DATA (id, entry) values (361, null);
insert into MOCK_DATA (id, entry) values (362, '17500-000');
insert into MOCK_DATA (id, entry) values (363, null);
insert into MOCK_DATA (id, entry) values (364, null);
insert into MOCK_DATA (id, entry) values (365, '66999');
insert into MOCK_DATA (id, entry) values (366, '44322');
insert into MOCK_DATA (id, entry) values (367, 'N8V');
insert into MOCK_DATA (id, entry) values (368, '368978');
insert into MOCK_DATA (id, entry) values (369, null);
insert into MOCK_DATA (id, entry) values (370, null);
insert into MOCK_DATA (id, entry) values (371, '6227');
insert into MOCK_DATA (id, entry) values (372, '5644');
insert into MOCK_DATA (id, entry) values (373, '8608');
insert into MOCK_DATA (id, entry) values (374, '357870');
insert into MOCK_DATA (id, entry) values (375, null);
insert into MOCK_DATA (id, entry) values (376, '09-200');
insert into MOCK_DATA (id, entry) values (377, null);
insert into MOCK_DATA (id, entry) values (378, null);
insert into MOCK_DATA (id, entry) values (379, '4730-062');
insert into MOCK_DATA (id, entry) values (380, '60105');
insert into MOCK_DATA (id, entry) values (381, '72121');
insert into MOCK_DATA (id, entry) values (382, '1011');
insert into MOCK_DATA (id, entry) values (383, '055448');
insert into MOCK_DATA (id, entry) values (384, null);
insert into MOCK_DATA (id, entry) values (385, '353983');
insert into MOCK_DATA (id, entry) values (386, null);
insert into MOCK_DATA (id, entry) values (387, '10505');
insert into MOCK_DATA (id, entry) values (388, null);
insert into MOCK_DATA (id, entry) values (389, '467 96');
insert into MOCK_DATA (id, entry) values (390, '94657 CEDEX');
insert into MOCK_DATA (id, entry) values (391, '75400-000');
insert into MOCK_DATA (id, entry) values (392, null);
insert into MOCK_DATA (id, entry) values (393, '941047');
insert into MOCK_DATA (id, entry) values (394, null);
insert into MOCK_DATA (id, entry) values (395, '51601');
insert into MOCK_DATA (id, entry) values (396, null);
insert into MOCK_DATA (id, entry) values (397, '9033');
insert into MOCK_DATA (id, entry) values (398, null);
insert into MOCK_DATA (id, entry) values (399, null);
insert into MOCK_DATA (id, entry) values (400, null);
insert into MOCK_DATA (id, entry) values (401, null);
insert into MOCK_DATA (id, entry) values (402, null);
insert into MOCK_DATA (id, entry) values (403, '299-4624');
insert into MOCK_DATA (id, entry) values (404, 'TXN');
insert into MOCK_DATA (id, entry) values (405, null);
insert into MOCK_DATA (id, entry) values (406, null);
insert into MOCK_DATA (id, entry) values (407, null);
insert into MOCK_DATA (id, entry) values (408, null);
insert into MOCK_DATA (id, entry) values (409, null);
insert into MOCK_DATA (id, entry) values (410, '44830-000');
insert into MOCK_DATA (id, entry) values (411, null);
insert into MOCK_DATA (id, entry) values (412, null);
insert into MOCK_DATA (id, entry) values (413, '188668');
insert into MOCK_DATA (id, entry) values (414, null);
insert into MOCK_DATA (id, entry) values (415, null);
insert into MOCK_DATA (id, entry) values (416, '97700-000');
insert into MOCK_DATA (id, entry) values (417, null);
insert into MOCK_DATA (id, entry) values (418, '446378');
insert into MOCK_DATA (id, entry) values (419, null);
insert into MOCK_DATA (id, entry) values (420, null);
insert into MOCK_DATA (id, entry) values (421, null);
insert into MOCK_DATA (id, entry) values (422, '297 32');
insert into MOCK_DATA (id, entry) values (423, null);
insert into MOCK_DATA (id, entry) values (424, null);
insert into MOCK_DATA (id, entry) values (425, null);
insert into MOCK_DATA (id, entry) values (426, '60637 CEDEX');
insert into MOCK_DATA (id, entry) values (427, '21251');
insert into MOCK_DATA (id, entry) values (428, null);
insert into MOCK_DATA (id, entry) values (429, '36205');
insert into MOCK_DATA (id, entry) values (430, null);
insert into MOCK_DATA (id, entry) values (431, null);
insert into MOCK_DATA (id, entry) values (432, '41821');
insert into MOCK_DATA (id, entry) values (433, '9013');
insert into MOCK_DATA (id, entry) values (434, '07-215');
insert into MOCK_DATA (id, entry) values (435, null);
insert into MOCK_DATA (id, entry) values (436, null);
insert into MOCK_DATA (id, entry) values (437, null);
insert into MOCK_DATA (id, entry) values (438, null);
insert into MOCK_DATA (id, entry) values (439, null);
insert into MOCK_DATA (id, entry) values (440, '5016');
insert into MOCK_DATA (id, entry) values (441, 'E3G');
insert into MOCK_DATA (id, entry) values (442, null);
insert into MOCK_DATA (id, entry) values (443, '120 16');
insert into MOCK_DATA (id, entry) values (444, '1045');
insert into MOCK_DATA (id, entry) values (445, '95123');
insert into MOCK_DATA (id, entry) values (446, null);
insert into MOCK_DATA (id, entry) values (447, null);
insert into MOCK_DATA (id, entry) values (448, null);
insert into MOCK_DATA (id, entry) values (449, '2629');
insert into MOCK_DATA (id, entry) values (450, '75110');
insert into MOCK_DATA (id, entry) values (451, '34-480');
insert into MOCK_DATA (id, entry) values (452, 'J9E');
insert into MOCK_DATA (id, entry) values (453, '668414');
insert into MOCK_DATA (id, entry) values (454, '692380');
insert into MOCK_DATA (id, entry) values (455, null);
insert into MOCK_DATA (id, entry) values (456, '654 68');
insert into MOCK_DATA (id, entry) values (457, null);
insert into MOCK_DATA (id, entry) values (458, null);
insert into MOCK_DATA (id, entry) values (459, '43850-000');
insert into MOCK_DATA (id, entry) values (460, null);
insert into MOCK_DATA (id, entry) values (461, '674660');
insert into MOCK_DATA (id, entry) values (462, null);
insert into MOCK_DATA (id, entry) values (463, null);
insert into MOCK_DATA (id, entry) values (464, '2725');
insert into MOCK_DATA (id, entry) values (465, '25220');
insert into MOCK_DATA (id, entry) values (466, '37-723');
insert into MOCK_DATA (id, entry) values (467, null);
insert into MOCK_DATA (id, entry) values (468, '601270');
insert into MOCK_DATA (id, entry) values (469, null);
insert into MOCK_DATA (id, entry) values (470, 'V9C');
insert into MOCK_DATA (id, entry) values (471, '413750');
insert into MOCK_DATA (id, entry) values (472, null);
insert into MOCK_DATA (id, entry) values (473, '68-213');
insert into MOCK_DATA (id, entry) values (474, null);
insert into MOCK_DATA (id, entry) values (475, 'N9V');
insert into MOCK_DATA (id, entry) values (476, '26010');
insert into MOCK_DATA (id, entry) values (477, null);
insert into MOCK_DATA (id, entry) values (478, '664 56');
insert into MOCK_DATA (id, entry) values (479, null);
insert into MOCK_DATA (id, entry) values (480, '95100');
insert into MOCK_DATA (id, entry) values (481, null);
insert into MOCK_DATA (id, entry) values (482, '64240-000');
insert into MOCK_DATA (id, entry) values (483, '2840');
insert into MOCK_DATA (id, entry) values (484, null);
insert into MOCK_DATA (id, entry) values (485, '12280-000');
insert into MOCK_DATA (id, entry) values (486, null);
insert into MOCK_DATA (id, entry) values (487, null);
insert into MOCK_DATA (id, entry) values (488, null);
insert into MOCK_DATA (id, entry) values (489, '764517');
insert into MOCK_DATA (id, entry) values (490, '95-083');
insert into MOCK_DATA (id, entry) values (491, null);
insert into MOCK_DATA (id, entry) values (492, null);
insert into MOCK_DATA (id, entry) values (493, '5972');
insert into MOCK_DATA (id, entry) values (494, '36200-000');
insert into MOCK_DATA (id, entry) values (495, '620908');
insert into MOCK_DATA (id, entry) values (496, '275 80');
insert into MOCK_DATA (id, entry) values (497, null);
insert into MOCK_DATA (id, entry) values (498, null);
insert into MOCK_DATA (id, entry) values (499, null);
insert into MOCK_DATA (id, entry) values (500, null);
insert into MOCK_DATA (id, entry) values (501, '18730-000');
insert into MOCK_DATA (id, entry) values (502, '1746');
insert into MOCK_DATA (id, entry) values (503, '183027');
insert into MOCK_DATA (id, entry) values (504, null);
insert into MOCK_DATA (id, entry) values (505, null);
insert into MOCK_DATA (id, entry) values (506, '446416');
insert into MOCK_DATA (id, entry) values (507, null);
insert into MOCK_DATA (id, entry) values (508, '478008');
insert into MOCK_DATA (id, entry) values (509, null);
insert into MOCK_DATA (id, entry) values (510, null);
insert into MOCK_DATA (id, entry) values (511, null);
insert into MOCK_DATA (id, entry) values (512, null);
insert into MOCK_DATA (id, entry) values (513, '32-436');
insert into MOCK_DATA (id, entry) values (514, '3513');
insert into MOCK_DATA (id, entry) values (515, '369160');
insert into MOCK_DATA (id, entry) values (516, null);
insert into MOCK_DATA (id, entry) values (517, '142672');
insert into MOCK_DATA (id, entry) values (518, null);
insert into MOCK_DATA (id, entry) values (519, '396130');
insert into MOCK_DATA (id, entry) values (520, '56564');
insert into MOCK_DATA (id, entry) values (521, '45149');
insert into MOCK_DATA (id, entry) values (522, null);
insert into MOCK_DATA (id, entry) values (523, null);
insert into MOCK_DATA (id, entry) values (524, '28890-000');
insert into MOCK_DATA (id, entry) values (525, '2710-151');
insert into MOCK_DATA (id, entry) values (526, null);
insert into MOCK_DATA (id, entry) values (527, null);
insert into MOCK_DATA (id, entry) values (528, '2519');
insert into MOCK_DATA (id, entry) values (529, '679 02');
insert into MOCK_DATA (id, entry) values (530, null);
insert into MOCK_DATA (id, entry) values (531, null);
insert into MOCK_DATA (id, entry) values (532, null);
insert into MOCK_DATA (id, entry) values (533, null);
insert into MOCK_DATA (id, entry) values (534, null);
insert into MOCK_DATA (id, entry) values (535, null);
insert into MOCK_DATA (id, entry) values (536, null);
insert into MOCK_DATA (id, entry) values (537, '676-0828');
insert into MOCK_DATA (id, entry) values (538, '69395 CEDEX 03');
insert into MOCK_DATA (id, entry) values (539, null);
insert into MOCK_DATA (id, entry) values (540, null);
insert into MOCK_DATA (id, entry) values (541, '08900-000');
insert into MOCK_DATA (id, entry) values (542, null);
insert into MOCK_DATA (id, entry) values (543, null);
insert into MOCK_DATA (id, entry) values (544, null);
insert into MOCK_DATA (id, entry) values (545, null);
insert into MOCK_DATA (id, entry) values (546, '2250-325');
insert into MOCK_DATA (id, entry) values (547, '3412');
insert into MOCK_DATA (id, entry) values (548, '39282');
insert into MOCK_DATA (id, entry) values (549, null);
insert into MOCK_DATA (id, entry) values (550, null);
insert into MOCK_DATA (id, entry) values (551, null);
insert into MOCK_DATA (id, entry) values (552, null);
insert into MOCK_DATA (id, entry) values (553, null);
insert into MOCK_DATA (id, entry) values (554, null);
insert into MOCK_DATA (id, entry) values (555, null);
insert into MOCK_DATA (id, entry) values (556, null);
insert into MOCK_DATA (id, entry) values (557, '05-622');
insert into MOCK_DATA (id, entry) values (558, null);
insert into MOCK_DATA (id, entry) values (559, '331 29');
insert into MOCK_DATA (id, entry) values (560, null);
insert into MOCK_DATA (id, entry) values (561, null);
insert into MOCK_DATA (id, entry) values (562, null);
insert into MOCK_DATA (id, entry) values (563, null);
insert into MOCK_DATA (id, entry) values (564, null);
insert into MOCK_DATA (id, entry) values (565, null);
insert into MOCK_DATA (id, entry) values (566, null);
insert into MOCK_DATA (id, entry) values (567, '4335');
insert into MOCK_DATA (id, entry) values (568, null);
insert into MOCK_DATA (id, entry) values (569, null);
insert into MOCK_DATA (id, entry) values (570, null);
insert into MOCK_DATA (id, entry) values (571, null);
insert into MOCK_DATA (id, entry) values (572, '27401');
insert into MOCK_DATA (id, entry) values (573, null);
insert into MOCK_DATA (id, entry) values (574, null);
insert into MOCK_DATA (id, entry) values (575, '94734 CEDEX');
insert into MOCK_DATA (id, entry) values (576, '15130');
insert into MOCK_DATA (id, entry) values (577, '618630');
insert into MOCK_DATA (id, entry) values (578, null);
insert into MOCK_DATA (id, entry) values (579, null);
insert into MOCK_DATA (id, entry) values (580, null);
insert into MOCK_DATA (id, entry) values (581, '67000-000');
insert into MOCK_DATA (id, entry) values (582, '822 30');
insert into MOCK_DATA (id, entry) values (583, null);
insert into MOCK_DATA (id, entry) values (584, null);
insert into MOCK_DATA (id, entry) values (585, null);
insert into MOCK_DATA (id, entry) values (586, null);
insert into MOCK_DATA (id, entry) values (587, null);
insert into MOCK_DATA (id, entry) values (588, null);
insert into MOCK_DATA (id, entry) values (589, '67110');
insert into MOCK_DATA (id, entry) values (590, '06-210');
insert into MOCK_DATA (id, entry) values (591, '20706');
insert into MOCK_DATA (id, entry) values (592, '7200-224');
insert into MOCK_DATA (id, entry) values (593, '273 71');
insert into MOCK_DATA (id, entry) values (594, '168 58');
insert into MOCK_DATA (id, entry) values (595, null);
insert into MOCK_DATA (id, entry) values (596, '65190');
insert into MOCK_DATA (id, entry) values (597, null);
insert into MOCK_DATA (id, entry) values (598, '111 61');
insert into MOCK_DATA (id, entry) values (599, null);
insert into MOCK_DATA (id, entry) values (600, null);
insert into MOCK_DATA (id, entry) values (601, null);
insert into MOCK_DATA (id, entry) values (602, '24890-000');
insert into MOCK_DATA (id, entry) values (603, '17270-000');
insert into MOCK_DATA (id, entry) values (604, null);
insert into MOCK_DATA (id, entry) values (605, '33-260');
insert into MOCK_DATA (id, entry) values (606, null);
insert into MOCK_DATA (id, entry) values (607, '13524 CEDEX');
insert into MOCK_DATA (id, entry) values (608, '4518');
insert into MOCK_DATA (id, entry) values (609, null);
insert into MOCK_DATA (id, entry) values (610, null);
insert into MOCK_DATA (id, entry) values (611, '21290');
insert into MOCK_DATA (id, entry) values (612, '3711');
insert into MOCK_DATA (id, entry) values (613, '271 37');
insert into MOCK_DATA (id, entry) values (614, null);
insert into MOCK_DATA (id, entry) values (615, '457 81');
insert into MOCK_DATA (id, entry) values (616, '94121');
insert into MOCK_DATA (id, entry) values (617, '69880-000');
insert into MOCK_DATA (id, entry) values (618, '741 72');
insert into MOCK_DATA (id, entry) values (619, '679230');
insert into MOCK_DATA (id, entry) values (620, '4710-627');
insert into MOCK_DATA (id, entry) values (621, null);
insert into MOCK_DATA (id, entry) values (622, '6001');
insert into MOCK_DATA (id, entry) values (623, null);
insert into MOCK_DATA (id, entry) values (624, null);
insert into MOCK_DATA (id, entry) values (625, null);
insert into MOCK_DATA (id, entry) values (626, null);
insert into MOCK_DATA (id, entry) values (627, '103 83');
insert into MOCK_DATA (id, entry) values (628, null);
insert into MOCK_DATA (id, entry) values (629, null);
insert into MOCK_DATA (id, entry) values (630, '52428');
insert into MOCK_DATA (id, entry) values (631, null);
insert into MOCK_DATA (id, entry) values (632, '64-020');
insert into MOCK_DATA (id, entry) values (633, null);
insert into MOCK_DATA (id, entry) values (634, '1320');
insert into MOCK_DATA (id, entry) values (635, '134507');
insert into MOCK_DATA (id, entry) values (636, '9200-088');
insert into MOCK_DATA (id, entry) values (637, '606525');
insert into MOCK_DATA (id, entry) values (638, '6548');
insert into MOCK_DATA (id, entry) values (639, '3261');
insert into MOCK_DATA (id, entry) values (640, '36200-000');
insert into MOCK_DATA (id, entry) values (641, null);
insert into MOCK_DATA (id, entry) values (642, '2519');
insert into MOCK_DATA (id, entry) values (643, '2655-082');
insert into MOCK_DATA (id, entry) values (644, '13681 CEDEX');
insert into MOCK_DATA (id, entry) values (645, '4805-081');
insert into MOCK_DATA (id, entry) values (646, null);
insert into MOCK_DATA (id, entry) values (647, null);
insert into MOCK_DATA (id, entry) values (648, null);
insert into MOCK_DATA (id, entry) values (649, '0247');
insert into MOCK_DATA (id, entry) values (650, null);
insert into MOCK_DATA (id, entry) values (651, '990-0054');
insert into MOCK_DATA (id, entry) values (652, '4032');
insert into MOCK_DATA (id, entry) values (653, '768 24');
insert into MOCK_DATA (id, entry) values (654, null);
insert into MOCK_DATA (id, entry) values (655, null);
insert into MOCK_DATA (id, entry) values (656, '94685 CEDEX');
insert into MOCK_DATA (id, entry) values (657, '09116');
insert into MOCK_DATA (id, entry) values (658, '8500');
insert into MOCK_DATA (id, entry) values (659, '93590');
insert into MOCK_DATA (id, entry) values (660, null);
insert into MOCK_DATA (id, entry) values (661, '1039');
insert into MOCK_DATA (id, entry) values (662, '2715-364');
insert into MOCK_DATA (id, entry) values (663, '11900-000');
insert into MOCK_DATA (id, entry) values (664, '75054 CEDEX 01');
insert into MOCK_DATA (id, entry) values (665, '869-0233');
insert into MOCK_DATA (id, entry) values (666, null);
insert into MOCK_DATA (id, entry) values (667, null);
insert into MOCK_DATA (id, entry) values (668, null);
insert into MOCK_DATA (id, entry) values (669, null);
insert into MOCK_DATA (id, entry) values (670, '33270');
insert into MOCK_DATA (id, entry) values (671, null);
insert into MOCK_DATA (id, entry) values (672, '3230');
insert into MOCK_DATA (id, entry) values (673, null);
insert into MOCK_DATA (id, entry) values (674, null);
insert into MOCK_DATA (id, entry) values (675, '613 81');
insert into MOCK_DATA (id, entry) values (676, '33805');
insert into MOCK_DATA (id, entry) values (677, null);
insert into MOCK_DATA (id, entry) values (678, null);
insert into MOCK_DATA (id, entry) values (679, null);
insert into MOCK_DATA (id, entry) values (680, null);
insert into MOCK_DATA (id, entry) values (681, '88-160');
insert into MOCK_DATA (id, entry) values (682, null);
insert into MOCK_DATA (id, entry) values (683, '35000');
insert into MOCK_DATA (id, entry) values (684, '37-112');
insert into MOCK_DATA (id, entry) values (685, null);
insert into MOCK_DATA (id, entry) values (686, null);
insert into MOCK_DATA (id, entry) values (687, '5801');
insert into MOCK_DATA (id, entry) values (688, null);
insert into MOCK_DATA (id, entry) values (689, '1191');
insert into MOCK_DATA (id, entry) values (690, null);
insert into MOCK_DATA (id, entry) values (691, '2732');
insert into MOCK_DATA (id, entry) values (692, null);
insert into MOCK_DATA (id, entry) values (693, null);
insert into MOCK_DATA (id, entry) values (694, null);
insert into MOCK_DATA (id, entry) values (695, null);
insert into MOCK_DATA (id, entry) values (696, null);
insert into MOCK_DATA (id, entry) values (697, '819-0014');
insert into MOCK_DATA (id, entry) values (698, '391 61');
insert into MOCK_DATA (id, entry) values (699, null);
insert into MOCK_DATA (id, entry) values (700, '59967 CEDEX');
insert into MOCK_DATA (id, entry) values (701, '171 78');
insert into MOCK_DATA (id, entry) values (702, '329-1117');
insert into MOCK_DATA (id, entry) values (703, 'V9L');
insert into MOCK_DATA (id, entry) values (704, null);
insert into MOCK_DATA (id, entry) values (705, '75660-000');
insert into MOCK_DATA (id, entry) values (706, '7450-265');
insert into MOCK_DATA (id, entry) values (707, '13841 CEDEX');
insert into MOCK_DATA (id, entry) values (708, '05-509');
insert into MOCK_DATA (id, entry) values (709, '1665');
insert into MOCK_DATA (id, entry) values (710, '13464 CEDEX 16');
insert into MOCK_DATA (id, entry) values (711, null);
insert into MOCK_DATA (id, entry) values (712, '5508');
insert into MOCK_DATA (id, entry) values (713, null);
insert into MOCK_DATA (id, entry) values (714, null);
insert into MOCK_DATA (id, entry) values (715, null);
insert into MOCK_DATA (id, entry) values (716, null);
insert into MOCK_DATA (id, entry) values (717, '29970');
insert into MOCK_DATA (id, entry) values (718, '461677');
insert into MOCK_DATA (id, entry) values (719, null);
insert into MOCK_DATA (id, entry) values (720, null);
insert into MOCK_DATA (id, entry) values (721, null);
insert into MOCK_DATA (id, entry) values (722, '446017');
insert into MOCK_DATA (id, entry) values (723, null);
insert into MOCK_DATA (id, entry) values (724, '607343');
insert into MOCK_DATA (id, entry) values (725, '739 41');
insert into MOCK_DATA (id, entry) values (726, null);
insert into MOCK_DATA (id, entry) values (727, null);
insert into MOCK_DATA (id, entry) values (728, null);
insert into MOCK_DATA (id, entry) values (729, '4314');
insert into MOCK_DATA (id, entry) values (730, null);
insert into MOCK_DATA (id, entry) values (731, '14160-000');
insert into MOCK_DATA (id, entry) values (732, '666 01');
insert into MOCK_DATA (id, entry) values (733, null);
insert into MOCK_DATA (id, entry) values (734, '86-105');
insert into MOCK_DATA (id, entry) values (735, null);
insert into MOCK_DATA (id, entry) values (736, '439 03');
insert into MOCK_DATA (id, entry) values (737, null);
insert into MOCK_DATA (id, entry) values (738, '93144 CEDEX');
insert into MOCK_DATA (id, entry) values (739, null);
insert into MOCK_DATA (id, entry) values (740, '2930');
insert into MOCK_DATA (id, entry) values (741, null);
insert into MOCK_DATA (id, entry) values (742, null);
insert into MOCK_DATA (id, entry) values (743, '18540-000');
insert into MOCK_DATA (id, entry) values (744, null);
insert into MOCK_DATA (id, entry) values (745, '6344');
insert into MOCK_DATA (id, entry) values (746, null);
insert into MOCK_DATA (id, entry) values (747, null);
insert into MOCK_DATA (id, entry) values (748, null);
insert into MOCK_DATA (id, entry) values (749, null);
insert into MOCK_DATA (id, entry) values (750, '3501');
insert into MOCK_DATA (id, entry) values (751, '92509 CEDEX');
insert into MOCK_DATA (id, entry) values (752, null);
insert into MOCK_DATA (id, entry) values (753, null);
insert into MOCK_DATA (id, entry) values (754, '456510');
insert into MOCK_DATA (id, entry) values (755, null);
insert into MOCK_DATA (id, entry) values (756, null);
insert into MOCK_DATA (id, entry) values (757, null);
insert into MOCK_DATA (id, entry) values (758, null);
insert into MOCK_DATA (id, entry) values (759, null);
insert into MOCK_DATA (id, entry) values (760, null);
insert into MOCK_DATA (id, entry) values (761, '91010');
insert into MOCK_DATA (id, entry) values (762, 'J4W');
insert into MOCK_DATA (id, entry) values (763, '795 92');
insert into MOCK_DATA (id, entry) values (764, null);
insert into MOCK_DATA (id, entry) values (765, '44-348');
insert into MOCK_DATA (id, entry) values (766, '309534');
insert into MOCK_DATA (id, entry) values (767, '735517');
insert into MOCK_DATA (id, entry) values (768, '125 71');
insert into MOCK_DATA (id, entry) values (769, null);
insert into MOCK_DATA (id, entry) values (770, '23120');
insert into MOCK_DATA (id, entry) values (771, '36441');
insert into MOCK_DATA (id, entry) values (772, '3300');
insert into MOCK_DATA (id, entry) values (773, null);
insert into MOCK_DATA (id, entry) values (774, '5815');
insert into MOCK_DATA (id, entry) values (775, null);
insert into MOCK_DATA (id, entry) values (776, '186018');
insert into MOCK_DATA (id, entry) values (777, '3830-017');
insert into MOCK_DATA (id, entry) values (778, null);
insert into MOCK_DATA (id, entry) values (779, '678149');
insert into MOCK_DATA (id, entry) values (780, null);
insert into MOCK_DATA (id, entry) values (781, '05-870');
insert into MOCK_DATA (id, entry) values (782, '71836');
insert into MOCK_DATA (id, entry) values (783, null);
insert into MOCK_DATA (id, entry) values (784, null);
insert into MOCK_DATA (id, entry) values (785, 'L-8708');
insert into MOCK_DATA (id, entry) values (786, null);
insert into MOCK_DATA (id, entry) values (787, null);
insert into MOCK_DATA (id, entry) values (788, '366406');
insert into MOCK_DATA (id, entry) values (789, null);
insert into MOCK_DATA (id, entry) values (790, null);
insert into MOCK_DATA (id, entry) values (791, null);
insert into MOCK_DATA (id, entry) values (792, '35460-000');
insert into MOCK_DATA (id, entry) values (793, null);
insert into MOCK_DATA (id, entry) values (794, 'J7Z');
insert into MOCK_DATA (id, entry) values (795, '93180');
insert into MOCK_DATA (id, entry) values (796, null);
insert into MOCK_DATA (id, entry) values (797, null);
insert into MOCK_DATA (id, entry) values (798, null);
insert into MOCK_DATA (id, entry) values (799, '309288');
insert into MOCK_DATA (id, entry) values (800, null);
insert into MOCK_DATA (id, entry) values (801, null);
insert into MOCK_DATA (id, entry) values (802, '10800');
insert into MOCK_DATA (id, entry) values (803, '3220-313');
insert into MOCK_DATA (id, entry) values (804, null);
insert into MOCK_DATA (id, entry) values (805, '374 53');
insert into MOCK_DATA (id, entry) values (806, '7447');
insert into MOCK_DATA (id, entry) values (807, null);
insert into MOCK_DATA (id, entry) values (808, '412950');
insert into MOCK_DATA (id, entry) values (809, '79165');
insert into MOCK_DATA (id, entry) values (810, null);
insert into MOCK_DATA (id, entry) values (811, '07509 CEDEX');
insert into MOCK_DATA (id, entry) values (812, null);
insert into MOCK_DATA (id, entry) values (813, '10125');
insert into MOCK_DATA (id, entry) values (814, null);
insert into MOCK_DATA (id, entry) values (815, null);
insert into MOCK_DATA (id, entry) values (816, null);
insert into MOCK_DATA (id, entry) values (817, null);
insert into MOCK_DATA (id, entry) values (818, null);
insert into MOCK_DATA (id, entry) values (819, '658183');
insert into MOCK_DATA (id, entry) values (820, '142817');
insert into MOCK_DATA (id, entry) values (821, null);
insert into MOCK_DATA (id, entry) values (822, null);
insert into MOCK_DATA (id, entry) values (823, '182157');
insert into MOCK_DATA (id, entry) values (824, null);
insert into MOCK_DATA (id, entry) values (825, '95930-000');
insert into MOCK_DATA (id, entry) values (826, null);
insert into MOCK_DATA (id, entry) values (827, null);
insert into MOCK_DATA (id, entry) values (828, '538 63');
insert into MOCK_DATA (id, entry) values (829, '427820');
insert into MOCK_DATA (id, entry) values (830, null);
insert into MOCK_DATA (id, entry) values (831, null);
insert into MOCK_DATA (id, entry) values (832, '30204');
insert into MOCK_DATA (id, entry) values (833, null);
insert into MOCK_DATA (id, entry) values (834, null);
insert into MOCK_DATA (id, entry) values (835, '411 10');
insert into MOCK_DATA (id, entry) values (836, null);
insert into MOCK_DATA (id, entry) values (837, '55530');
insert into MOCK_DATA (id, entry) values (838, '403 40');
insert into MOCK_DATA (id, entry) values (839, null);
insert into MOCK_DATA (id, entry) values (840, '89024 CEDEX');
insert into MOCK_DATA (id, entry) values (841, null);
insert into MOCK_DATA (id, entry) values (842, null);
insert into MOCK_DATA (id, entry) values (843, '157860');
insert into MOCK_DATA (id, entry) values (844, '83280-000');
insert into MOCK_DATA (id, entry) values (845, null);
insert into MOCK_DATA (id, entry) values (846, '16-515');
insert into MOCK_DATA (id, entry) values (847, '15830-000');
insert into MOCK_DATA (id, entry) values (848, null);
insert into MOCK_DATA (id, entry) values (849, '56700');
insert into MOCK_DATA (id, entry) values (850, null);
insert into MOCK_DATA (id, entry) values (851, '5602');
insert into MOCK_DATA (id, entry) values (852, '15880');
insert into MOCK_DATA (id, entry) values (853, '5602');
insert into MOCK_DATA (id, entry) values (854, '58501');
insert into MOCK_DATA (id, entry) values (855, null);
insert into MOCK_DATA (id, entry) values (856, null);
insert into MOCK_DATA (id, entry) values (857, null);
insert into MOCK_DATA (id, entry) values (858, '98400-000');
insert into MOCK_DATA (id, entry) values (859, null);
insert into MOCK_DATA (id, entry) values (860, '77000-000');
insert into MOCK_DATA (id, entry) values (861, null);
insert into MOCK_DATA (id, entry) values (862, null);
insert into MOCK_DATA (id, entry) values (863, '13390-000');
insert into MOCK_DATA (id, entry) values (864, null);
insert into MOCK_DATA (id, entry) values (865, null);
insert into MOCK_DATA (id, entry) values (866, null);
insert into MOCK_DATA (id, entry) values (867, null);
insert into MOCK_DATA (id, entry) values (868, '4126');
insert into MOCK_DATA (id, entry) values (869, null);
insert into MOCK_DATA (id, entry) values (870, null);
insert into MOCK_DATA (id, entry) values (871, null);
insert into MOCK_DATA (id, entry) values (872, '2208');
insert into MOCK_DATA (id, entry) values (873, null);
insert into MOCK_DATA (id, entry) values (874, null);
insert into MOCK_DATA (id, entry) values (875, '150607');
insert into MOCK_DATA (id, entry) values (876, null);
insert into MOCK_DATA (id, entry) values (877, '29755');
insert into MOCK_DATA (id, entry) values (878, null);
insert into MOCK_DATA (id, entry) values (879, null);
insert into MOCK_DATA (id, entry) values (880, '28200-000');
insert into MOCK_DATA (id, entry) values (881, null);
insert into MOCK_DATA (id, entry) values (882, '9002');
insert into MOCK_DATA (id, entry) values (883, '5311');
insert into MOCK_DATA (id, entry) values (884, null);
insert into MOCK_DATA (id, entry) values (885, null);
insert into MOCK_DATA (id, entry) values (886, null);
insert into MOCK_DATA (id, entry) values (887, null);
insert into MOCK_DATA (id, entry) values (888, '64650');
insert into MOCK_DATA (id, entry) values (889, '414 71');
insert into MOCK_DATA (id, entry) values (890, '20601');
insert into MOCK_DATA (id, entry) values (891, '353810');
insert into MOCK_DATA (id, entry) values (892, '87066 CEDEX 2');
insert into MOCK_DATA (id, entry) values (893, '93907');
insert into MOCK_DATA (id, entry) values (894, null);
insert into MOCK_DATA (id, entry) values (895, '735 72');
insert into MOCK_DATA (id, entry) values (896, null);
insert into MOCK_DATA (id, entry) values (897, null);
insert into MOCK_DATA (id, entry) values (898, null);
insert into MOCK_DATA (id, entry) values (899, '75604 CEDEX 12');
insert into MOCK_DATA (id, entry) values (900, '188355');
insert into MOCK_DATA (id, entry) values (901, 'MD-4233');
insert into MOCK_DATA (id, entry) values (902, null);
insert into MOCK_DATA (id, entry) values (903, null);
insert into MOCK_DATA (id, entry) values (904, '606860');
insert into MOCK_DATA (id, entry) values (905, '3801');
insert into MOCK_DATA (id, entry) values (906, null);
insert into MOCK_DATA (id, entry) values (907, null);
insert into MOCK_DATA (id, entry) values (908, null);
insert into MOCK_DATA (id, entry) values (909, '35900-000');
insert into MOCK_DATA (id, entry) values (910, null);
insert into MOCK_DATA (id, entry) values (911, '398 51');
insert into MOCK_DATA (id, entry) values (912, null);
insert into MOCK_DATA (id, entry) values (913, '3611');
insert into MOCK_DATA (id, entry) values (914, '43-188');
insert into MOCK_DATA (id, entry) values (915, null);
insert into MOCK_DATA (id, entry) values (916, null);
insert into MOCK_DATA (id, entry) values (917, null);
insert into MOCK_DATA (id, entry) values (918, null);
insert into MOCK_DATA (id, entry) values (919, null);
insert into MOCK_DATA (id, entry) values (920, '20101');
insert into MOCK_DATA (id, entry) values (921, null);
insert into MOCK_DATA (id, entry) values (922, null);
insert into MOCK_DATA (id, entry) values (923, '2432');
insert into MOCK_DATA (id, entry) values (924, '981-1505');
insert into MOCK_DATA (id, entry) values (925, 'P24');
insert into MOCK_DATA (id, entry) values (926, '3814');
insert into MOCK_DATA (id, entry) values (927, '3474');
insert into MOCK_DATA (id, entry) values (928, '961 73');
insert into MOCK_DATA (id, entry) values (929, null);
insert into MOCK_DATA (id, entry) values (930, null);
insert into MOCK_DATA (id, entry) values (931, null);
insert into MOCK_DATA (id, entry) values (932, '1865');
insert into MOCK_DATA (id, entry) values (933, '11801');
insert into MOCK_DATA (id, entry) values (934, null);
insert into MOCK_DATA (id, entry) values (935, null);
insert into MOCK_DATA (id, entry) values (936, null);
insert into MOCK_DATA (id, entry) values (937, null);
insert into MOCK_DATA (id, entry) values (938, null);
insert into MOCK_DATA (id, entry) values (939, null);
insert into MOCK_DATA (id, entry) values (940, null);
insert into MOCK_DATA (id, entry) values (941, '37924');
insert into MOCK_DATA (id, entry) values (942, '2905');
insert into MOCK_DATA (id, entry) values (943, null);
insert into MOCK_DATA (id, entry) values (944, null);
insert into MOCK_DATA (id, entry) values (945, null);
insert into MOCK_DATA (id, entry) values (946, null);
insert into MOCK_DATA (id, entry) values (947, null);
insert into MOCK_DATA (id, entry) values (948, null);
insert into MOCK_DATA (id, entry) values (949, null);
insert into MOCK_DATA (id, entry) values (950, null);
insert into MOCK_DATA (id, entry) values (951, '78379 CEDEX');
insert into MOCK_DATA (id, entry) values (952, '44880-000');
insert into MOCK_DATA (id, entry) values (953, null);
insert into MOCK_DATA (id, entry) values (954, '13190');
insert into MOCK_DATA (id, entry) values (955, null);
insert into MOCK_DATA (id, entry) values (956, null);
insert into MOCK_DATA (id, entry) values (957, null);
insert into MOCK_DATA (id, entry) values (958, null);
insert into MOCK_DATA (id, entry) values (959, '357217');
insert into MOCK_DATA (id, entry) values (960, '216646');
insert into MOCK_DATA (id, entry) values (961, null);
insert into MOCK_DATA (id, entry) values (962, null);
insert into MOCK_DATA (id, entry) values (963, null);
insert into MOCK_DATA (id, entry) values (964, null);
insert into MOCK_DATA (id, entry) values (965, null);
insert into MOCK_DATA (id, entry) values (966, null);
insert into MOCK_DATA (id, entry) values (967, null);
insert into MOCK_DATA (id, entry) values (968, '10290');
insert into MOCK_DATA (id, entry) values (969, '43-410');
insert into MOCK_DATA (id, entry) values (970, null);
insert into MOCK_DATA (id, entry) values (971, '309509');
insert into MOCK_DATA (id, entry) values (972, 'D12');
insert into MOCK_DATA (id, entry) values (973, null);
insert into MOCK_DATA (id, entry) values (974, '77110');
insert into MOCK_DATA (id, entry) values (975, '181280');
insert into MOCK_DATA (id, entry) values (976, '0264');
insert into MOCK_DATA (id, entry) values (977, '696 65');
insert into MOCK_DATA (id, entry) values (978, null);
insert into MOCK_DATA (id, entry) values (979, '4085');
insert into MOCK_DATA (id, entry) values (980, null);
insert into MOCK_DATA (id, entry) values (981, '190 12');
insert into MOCK_DATA (id, entry) values (982, '936-0056');
insert into MOCK_DATA (id, entry) values (983, '94039 CEDEX');
insert into MOCK_DATA (id, entry) values (984, null);
insert into MOCK_DATA (id, entry) values (985, null);
insert into MOCK_DATA (id, entry) values (986, '601974');
insert into MOCK_DATA (id, entry) values (987, 'D09');
insert into MOCK_DATA (id, entry) values (988, '87930 CEDEX 9');
insert into MOCK_DATA (id, entry) values (989, null);
insert into MOCK_DATA (id, entry) values (990, null);
insert into MOCK_DATA (id, entry) values (991, null);
insert into MOCK_DATA (id, entry) values (992, '160555');
insert into MOCK_DATA (id, entry) values (993, '626-0072');
insert into MOCK_DATA (id, entry) values (994, null);
insert into MOCK_DATA (id, entry) values (995, null);
insert into MOCK_DATA (id, entry) values (996, '77806');
insert into MOCK_DATA (id, entry) values (997, '5002');
insert into MOCK_DATA (id, entry) values (998, null);
insert into MOCK_DATA (id, entry) values (999, null);
insert into MOCK_DATA (id, entry) values (1000, '569-0036');
